master

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,43 +1,51 @@
 #!/bin/sh
-#set -e
+set -e
 
-#sudo chmod u+x *.sh
-
-sudo yum install createrepo --disablerepo=localrepo
-
-if [ ! -f /etc/yum.repos.d/localrepo.repo ]; then
-sudo mkdir -p /usr/localrepo/
-sudo cp -vn ./devtools/* /usr/localrepo/
-sudo cp -vn ./localrepo.repo /etc/yum.repos.d/localrepo.repo
-sudo createrepo -v /usr/localrepo/
-sudo yum-config-manager --enable localrepo
-sudo yum clean all
-sudo yum update
+if [ -f /etc/debian_version ]; then
+    for package in python-pip python-virtualenv python-dev libevent-dev libffi-dev libxml2-dev libxslt-dev zlib1g-dev; do
+        if [ "$(dpkg --status -- $package 2>/dev/null|sed -n 's/^Status: //p')" != "install ok installed" ]; then
+            # add a space after old values
+            missing="${missing:+$missing }$package"
+        fi
+    done
+    if [ -n "$missing" ]; then
+        echo "$0: missing required DEB packages. Installing via sudo." 1>&2
+        sudo apt-get -y install $missing
+    fi
+elif [ -f /etc/fedora-release ]; then
+    for package in python-pip python2-virtualenv python-devel libevent-devel libffi-devel libxml2-devel libxslt-devel zlib-devel; do
+        if [ "$(rpm -qa $package 2>/dev/null)" == "" ]; then
+            missing="${missing:+$missing }$package"
+        fi
+    done
+    if [ -n "$missing" ]; then
+        echo "$0: missing required RPM packages. Installing via sudo." 1>&2
+        sudo yum -y install $missing
+    fi
+elif [ -f /etc/redhat-release ]; then
+    for package in python-virtualenv python-devel libevent-devel libffi-devel libxml2-devel libxslt-devel zlib-devel; do
+        if [ "$(rpm -qa $package 2>/dev/null)" == "" ]; then
+            missing="${missing:+$missing }$package"
+        fi
+    done
+    if [ -n "$missing" ]; then
+        echo "$0: missing required RPM packages. Installing via sudo." 1>&2
+        sudo yum -y install $missing
+    fi
 fi
-
-cd devtools
-sudo rpm -i --nodeps *.rpm
-cd ..
-
-#if [ -f /etc/redhat-release ]; then
-#    for package in $(cat deplist) ; do
-#        if [ "$(rpm -qa $package 2>/dev/null)" = "" ]; then
-#            missing="${missing:+$missing }$package"
-#        fi
-#    done
-#    if [ -n "$missing" ]; then
-#        echo "$missing"
-#        echo "$0: missing required RPM packages. Installing via sudo." 1>&2
-#        sudo yum install -y $missing
-#    fi
-#fi
 
 virtualenv --no-site-packages --distribute virtualenv
 
-./virtualenv/bin/pip install --no-index --find-links="./piprepo" -r requirements.txt
+# avoid pip bugs
+./virtualenv/bin/pip install --upgrade pip
 
+# slightly old version of setuptools; newer fails w/ requests 0.14.0
+./virtualenv/bin/pip install setuptools==32.3.1
+
+./virtualenv/bin/pip install -r requirements.txt
+
+# forbid setuptools from using the network because it'll try to use
+# easy_install, and we really wanted pip; next line will fail if pip
+# requirements.txt does not match setup.py requirements -- sucky but
+# good enough for now
 ./virtualenv/bin/python setup.py develop
-
-if [ ! -f ~/.s3cfg ]; then
-    echo "s3cmd not configured.\n$USER# s3cmd --configure" && exit 0
-fi
