Rollback to Boto2

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,20 +1,16 @@
-#!/bin/bash
-
-sudo chmod +x -R run_all.sh scripts/*
+#!/bin/sh
+set -e
 
 if [ -f /etc/redhat-release ]; then
-	sudo rpm -ivh dependencies/python-devel-2.7.5-80.el7_6.x86_64.rpm --nodeps
-	sudo yum localinstall dependencies/rpms/* --nogpgcheck -y
-#	sudo rpm -ivh dependencies/perl/* --nodeps
-	sudo rpm -ivh dependencies/perl/perl-Data-Dumper-2.145-3.el7.x86_64.rpm --nodeps
-	sudo rpm -ivh dependencies/perl/perl-Error-0.17020-2.el7.noarch.rpm --nodeps
-	sudo rpm -ivh dependencies/perl/perl-Git-1.8.3.1-20.el7.noarch.rpm --nodeps
-	sudo rpm -ivh dependencies/perl/perl-TermReadKey-2.30-20.el7.x86_64.rpm --nodeps
-	sudo rpm -ivh dependencies/perl/perl-XML-LibXML-2.0018-5.el7.x86_64.rpm --nodeps
-	sudo rpm -ivh dependencies/perl/perl-XML-NamespaceSupport-1.11-10.el7.noarch.rpm --nodeps
-	sudo rpm -ivh dependencies/perl/perl-XML-SAX-0.99-9.el7.noarch.rpm --nodeps
-	sudo rpm -ivh dependencies/perl/perl-XML-SAX-Base-1.08-7.el7.noarch.rpm --nodeps
-	sudo rpm -ivh dependencies/perl/perl-XML-Simple-2.20-5.el7.noarch.rpm --nodeps
+    for package in python-virtualenv python-devel libevent-devel libffi-devel libxml2-devel libxslt-devel zlib-devel; do
+        if [ "$(rpm -qa $package 2>/dev/null)" == "" ]; then
+            missing="${missing:+$missing }$package"
+        fi
+    done
+    if [ -n "$missing" ]; then
+        echo "$0: missing required RPM packages. Installing via sudo." 1>&2
+        sudo yum -y install $missing
+    fi
 fi
 
 if [ -f certificates/Citi_DEVELOPMENT_chain.pem ]; then
@@ -22,12 +18,21 @@ if [ -f certificates/Citi_DEVELOPMENT_chain.pem ]; then
   sudo update-ca-trust extract
 fi
 
-virtualenv --python=$(which python2) --no-site-packages --distribute virtualenv
-virtualenv/bin/pip install --upgrade pip --no-index --find-links="dependencies/pip/"
-virtualenv/bin/pip install setuptools==32.3.1 --no-index --find-links="dependencies/pip/"
-virtualenv/bin/pip install -r requirements.txt --no-index --find-links="dependencies/pip/"
-virtualenv/bin/python setup.py develop
+virtualenv --no-site-packages --distribute virtualenv
 
-pip install -r requirements-local.txt --no-index --user --find-links="dependencies/pip/"
+# avoid pip bugs
+./virtualenv/bin/pip install --upgrade pip --no-index --find-links="dependencies/pip/"
 
-echo -en "Build complete\n"
+# slightly old version of setuptools; newer fails w/ requests 0.14.0
+./virtualenv/bin/pip install setuptools==32.3.1 --no-index --find-links="dependencies/pip/"
+
+./virtualenv/bin/pip install -r requirements.txt --no-index --find-links="dependencies/pip/"
+
+# forbid setuptools from using the network because it'll try to use
+# easy_install, and we really wanted pip; next line will fail if pip
+# requirements.txt does not match setup.py requirements -- sucky but
+# good enough for now
+./virtualenv/bin/python setup.py develop
+
+# for use with local scripts
+#pip install -r requirements-local.txt --no-index --user --find-links="dependencies/pip/"
